#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum {
    TD_SPC_DOT,
    TD_COLN_SCLN,
    TD_N_EQL,
    TD_LCBR_LBRC,
    TD_RCBR_RBRC,
};

// Tap Dance definitions
tap_dance_action_t tap_dance_actions[] = {
    // Tap once for Escape, twice for Caps Lock
    [TD_SPC_DOT] = ACTION_TAP_DANCE_DOUBLE(KC_SPC, KC_DOT),
    [TD_COLN_SCLN] = ACTION_TAP_DANCE_DOUBLE(KC_COLN, KC_SCLN),
    [TD_N_EQL] = ACTION_TAP_DANCE_DOUBLE(KC_N, KC_EQL),
    [TD_LCBR_LBRC] = ACTION_TAP_DANCE_DOUBLE(KC_LCBR, KC_LBRC),
    [TD_RCBR_RBRC] = ACTION_TAP_DANCE_DOUBLE(KC_RCBR, KC_RBRC),

};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_3x5_2(KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_TAB, LALT(KC_Z), LSFT_T(KC_X), LCTL_T(KC_C), LGUI_T(KC_V), KC_B, TD(TD_N_EQL), RGUI_T(KC_M), RCTL_T(KC_SLSH), RSFT_T(KC_DOT), TD(TD_COLN_SCLN), KC_BSPC, TD(TD_SPC_DOT), KC_ENT, TG(1)),
	[1] = LAYOUT_split_3x5_2(KC_ESC, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_SCLN, KC_BSPC, KC_PLUS, KC_EQL, KC_MINS, KC_UNDS, KC_QUOT, KC_BSLS, TD(TD_LCBR_LBRC), TD(TD_RCBR_RBRC), KC_PIPE, KC_TAB, KC_TILD, KC_HASH, KC_EXLM, KC_SCLN, KC_DQUO, KC_LT, KC_LPRN, KC_RPRN, KC_GT, TG(3), TG(1), KC_SPC, KC_ENT, TG(3)),
	[2] = LAYOUT_split_3x5_2(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MINS, KC_7, KC_8, KC_9, KC_BSPC, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_EQL, KC_4, KC_5, KC_6, KC_ENT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_0, KC_1, KC_2, KC_3, TG(2), TG(1), KC_SPC, KC_ENT, TG(3))
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)





